/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siaco.views.Internal;

import siaco.views.BOASVINDAS;

/**
 *
 * @author Tiago
 */
public class InternalFrameCotações extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameBemvindo
     */
    public InternalFrameCotações() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirCotacao = new javax.swing.JButton();
        AbrirCotacao1 = new javax.swing.JButton();
        AbrirCotacao2 = new javax.swing.JButton();
        LSeuHistorico = new javax.swing.JLabel();
        LCotaçõesFechadas = new javax.swing.JLabel();
        LCotaçõesemAberto = new javax.swing.JLabel();
        Historico = new javax.swing.JLabel();
        CotaçõesAbertas = new javax.swing.JLabel();
        CotaçõesFechadas = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setBackground(null);
        setBorder(null);
        setClosable(true);
        setTitle("Bem vindo");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbrirCotacao.setBackground(new java.awt.Color(255, 153, 0));
        AbrirCotacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AbrirCotacao.setForeground(new java.awt.Color(255, 255, 255));
        AbrirCotacao.setText("Financeiro");
        AbrirCotacao.setBorder(null);
        AbrirCotacao.setBorderPainted(false);
        AbrirCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCotacaoActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirCotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 250, 100));

        AbrirCotacao1.setBackground(new java.awt.Color(0, 0, 255));
        AbrirCotacao1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AbrirCotacao1.setForeground(new java.awt.Color(255, 255, 255));
        AbrirCotacao1.setText("Abrir Cotação");
        AbrirCotacao1.setBorder(null);
        AbrirCotacao1.setBorderPainted(false);
        AbrirCotacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCotacao1ActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirCotacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 150, 250, 100));

        AbrirCotacao2.setBackground(new java.awt.Color(204, 0, 0));
        AbrirCotacao2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AbrirCotacao2.setForeground(new java.awt.Color(255, 255, 255));
        AbrirCotacao2.setText("Fechar");
        AbrirCotacao2.setBorder(null);
        AbrirCotacao2.setBorderPainted(false);
        AbrirCotacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCotacao2ActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirCotacao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, 250, 100));

        LSeuHistorico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LSeuHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTESCOTAÇÃO/Grupo 44.png"))); // NOI18N
        getContentPane().add(LSeuHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 320, 60));

        LCotaçõesFechadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LCotaçõesFechadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTESCOTAÇÃO/Grupo 43.png"))); // NOI18N
        getContentPane().add(LCotaçõesFechadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 320, 60));

        LCotaçõesemAberto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LCotaçõesemAberto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTESCOTAÇÃO/Grupo 42.png"))); // NOI18N
        getContentPane().add(LCotaçõesemAberto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 60));

        Historico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPO..BOASVINDAS/Rectangle 8.png"))); // NOI18N
        getContentPane().add(Historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 320, 780));

        CotaçõesAbertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPO..BOASVINDAS/Rectangle 8.png"))); // NOI18N
        getContentPane().add(CotaçõesAbertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 780));

        CotaçõesFechadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPO..BOASVINDAS/Rectangle 8.png"))); // NOI18N
        getContentPane().add(CotaçõesFechadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 320, 780));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPO..BOASVINDAS/Background geral.png"))); // NOI18N
        BackGround.setText("jLabel1");
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1280, 780));

        setBounds(0, 0, 1250, 800);
    }// </editor-fold>//GEN-END:initComponents

    private void AbrirCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCotacaoActionPerformed

    }//GEN-LAST:event_AbrirCotacaoActionPerformed

    private void AbrirCotacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCotacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbrirCotacao1ActionPerformed

    private void AbrirCotacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCotacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbrirCotacao2ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirCotacao;
    private javax.swing.JButton AbrirCotacao1;
    private javax.swing.JButton AbrirCotacao2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JLabel CotaçõesAbertas;
    private javax.swing.JLabel CotaçõesFechadas;
    private javax.swing.JLabel Historico;
    private javax.swing.JLabel LCotaçõesFechadas;
    private javax.swing.JLabel LCotaçõesemAberto;
    private javax.swing.JLabel LSeuHistorico;
    // End of variables declaration//GEN-END:variables
}
