/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siaco.views.Internal;

import siaco.views.BOASVINDAS;

/**
 *
 * @author Tiago
 */
public class InternalFrameBemvindo extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameBemvindo
     */
    public InternalFrameBemvindo() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirCotacao = new javax.swing.JButton();
        emAndamento = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

        setBackground(null);
        setBorder(null);
        setClosable(true);
        setTitle("Bem vindo");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbrirCotacao.setBackground(new java.awt.Color(0, 0, 255));
        AbrirCotacao.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        AbrirCotacao.setForeground(new java.awt.Color(255, 255, 255));
        AbrirCotacao.setText("Abrir Cotação");
        AbrirCotacao.setBorder(null);
        AbrirCotacao.setBorderPainted(false);
        AbrirCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCotacaoActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirCotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 402, 180));

        emAndamento.setBackground(new java.awt.Color(255, 153, 0));
        emAndamento.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        emAndamento.setForeground(new java.awt.Color(255, 255, 255));
        emAndamento.setText("Em Andamento");
        emAndamento.setBorder(null);
        emAndamento.setBorderPainted(false);
        emAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emAndamentoActionPerformed(evt);
            }
        });
        getContentPane().add(emAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 402, 180));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPO..BOASVINDAS/Background geral.png"))); // NOI18N
        BackGround.setText("jLabel1");
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 1280, 780));

        setBounds(0, 0, 1250, 800);
    }// </editor-fold>//GEN-END:initComponents
    
    private void AbrirCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCotacaoActionPerformed
        
    }//GEN-LAST:event_AbrirCotacaoActionPerformed

    private void emAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emAndamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emAndamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirCotacao;
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton emAndamento;
    // End of variables declaration//GEN-END:variables
}
