/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siaco.views.Internal;

import siaco.views.BOASVINDAS;

/**
 *
 * @author Tiago
 */
public class InternalFrameListaProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrameBemvindo
     */
    public InternalFrameListaProdutos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AbrirCotacao = new javax.swing.JButton();
        emAndamento = new javax.swing.JButton();
        AbrirCotacao1 = new javax.swing.JButton();
        AbrirCotacao2 = new javax.swing.JButton();
        BackGround = new javax.swing.JLabel();

        setBackground(null);
        setBorder(null);
        setClosable(true);
        setTitle("Lista de Produtos");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AbrirCotacao.setBackground(new java.awt.Color(0, 204, 102));
        AbrirCotacao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AbrirCotacao.setForeground(new java.awt.Color(255, 255, 255));
        AbrirCotacao.setText("Imprimir/Enviar");
        AbrirCotacao.setBorder(null);
        AbrirCotacao.setBorderPainted(false);
        AbrirCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCotacaoActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirCotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 270, 80));

        emAndamento.setBackground(new java.awt.Color(102, 51, 204));
        emAndamento.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        emAndamento.setForeground(new java.awt.Color(255, 255, 255));
        emAndamento.setText("Minha Lista");
        emAndamento.setBorder(null);
        emAndamento.setBorderPainted(false);
        emAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emAndamentoActionPerformed(evt);
            }
        });
        getContentPane().add(emAndamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 270, 80));

        AbrirCotacao1.setBackground(new java.awt.Color(0, 0, 255));
        AbrirCotacao1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AbrirCotacao1.setForeground(new java.awt.Color(255, 255, 255));
        AbrirCotacao1.setText("Criar Lista");
        AbrirCotacao1.setBorder(null);
        AbrirCotacao1.setBorderPainted(false);
        AbrirCotacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCotacao1ActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirCotacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 270, 80));

        AbrirCotacao2.setBackground(new java.awt.Color(204, 153, 0));
        AbrirCotacao2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AbrirCotacao2.setForeground(new java.awt.Color(255, 255, 255));
        AbrirCotacao2.setText("Favoritos");
        AbrirCotacao2.setBorder(null);
        AbrirCotacao2.setBorderPainted(false);
        AbrirCotacao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirCotacao2ActionPerformed(evt);
            }
        });
        getContentPane().add(AbrirCotacao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 270, 80));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPO..BOASVINDAS/Background geral.png"))); // NOI18N
        BackGround.setText("jLabel1");
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-390, 0, 1280, 780));

        setBounds(0, 0, 750, 650);
    }// </editor-fold>//GEN-END:initComponents
    
    private void AbrirCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCotacaoActionPerformed
        
    }//GEN-LAST:event_AbrirCotacaoActionPerformed

    private void emAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emAndamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emAndamentoActionPerformed

    private void AbrirCotacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCotacao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbrirCotacao1ActionPerformed

    private void AbrirCotacao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirCotacao2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbrirCotacao2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirCotacao;
    private javax.swing.JButton AbrirCotacao1;
    private javax.swing.JButton AbrirCotacao2;
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton emAndamento;
    // End of variables declaration//GEN-END:variables
}
