/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siaco.views.Internal;

/**
 *
 * @author Tiago
 */
public class Jframedescrição extends javax.swing.JFrame {

    /**
     * Creates new form Jframedescrição
     */
    public Jframedescrição() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCaracteristica = new javax.swing.JPanel();
        JLabelCaracteristica = new javax.swing.JLabel();
        jLabelCOR = new javax.swing.JLabel();
        jLabelMODELO = new javax.swing.JLabel();
        jLabelMARCA = new javax.swing.JLabel();
        jTextFieldCOR = new javax.swing.JTextField();
        jTextFieldCOR1 = new javax.swing.JTextField();
        jTextFieldCOR2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JLabelCaracteristica.setText("Característica ");

        jLabelCOR.setText("COR");

        jLabelMODELO.setText("MODELO");

        jLabelMARCA.setText("MARCA");

        jTextFieldCOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCORActionPerformed(evt);
            }
        });

        jTextFieldCOR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCOR1ActionPerformed(evt);
            }
        });

        jTextFieldCOR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCOR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCaracteristicaLayout = new javax.swing.GroupLayout(jPanelCaracteristica);
        jPanelCaracteristica.setLayout(jPanelCaracteristicaLayout);
        jPanelCaracteristicaLayout.setHorizontalGroup(
            jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaracteristicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabelCaracteristica)
                    .addGroup(jPanelCaracteristicaLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMODELO)
                            .addComponent(jLabelCOR)
                            .addComponent(jLabelMARCA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCOR2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCOR, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCOR1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanelCaracteristicaLayout.setVerticalGroup(
            jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaracteristicaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(JLabelCaracteristica)
                .addGap(18, 18, 18)
                .addGroup(jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCOR)
                    .addComponent(jTextFieldCOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMODELO)
                    .addComponent(jTextFieldCOR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCaracteristicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMARCA)
                    .addComponent(jTextFieldCOR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCaracteristica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCaracteristica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCORActionPerformed

    private void jTextFieldCOR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCOR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCOR1ActionPerformed

    private void jTextFieldCOR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCOR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCOR2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframedescrição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframedescrição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframedescrição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframedescrição.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jframedescrição().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelCaracteristica;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCOR;
    private javax.swing.JLabel jLabelMARCA;
    private javax.swing.JLabel jLabelMODELO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCaracteristica;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCOR;
    private javax.swing.JTextField jTextFieldCOR1;
    private javax.swing.JTextField jTextFieldCOR2;
    // End of variables declaration//GEN-END:variables
}
