/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siaco.views;

/**
 *
 * @author Adrielly Rayssa
 */
public class LOGINPRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form LOGINPRINCIPAL
     */
    public LOGINPRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonFornecedor = new javax.swing.JButton();
        ButtonComprador = new javax.swing.JButton();
        ButtonCadastrar = new javax.swing.JToggleButton();
        barrasenha = new javax.swing.JLabel();
        Barracentral = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1293, 761));
        setResizable(false);
        setSize(new java.awt.Dimension(1293, 761));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonFornecedor.setBackground(new java.awt.Color(0, 0, 0));
        ButtonFornecedor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        ButtonFornecedor.setText("Fornecedor");
        ButtonFornecedor.setActionCommand("");
        ButtonFornecedor.setBorderPainted(false);
        ButtonFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 190, 40));

        ButtonComprador.setBackground(new java.awt.Color(0, 0, 0));
        ButtonComprador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonComprador.setForeground(new java.awt.Color(255, 255, 255));
        ButtonComprador.setText("Comprador");
        ButtonComprador.setBorderPainted(false);
        getContentPane().add(ButtonComprador, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 190, 40));

        ButtonCadastrar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTES-LOGINPRINCIPAL/Cadastrar.png"))); // NOI18N
        ButtonCadastrar.setBorderPainted(false);
        ButtonCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCadastrarMouseClicked(evt);
            }
        });
        ButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 190, 40));

        barrasenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTES-LOGINPRINCIPAL/Rectangle 2.png"))); // NOI18N
        getContentPane().add(barrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(-550, 430, 1840, 110));

        Barracentral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTES-LOGINPRINCIPAL/Group 5.png"))); // NOI18N
        Barracentral.setText("jLabel1");
        getContentPane().add(Barracentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, 250, 1600, 180));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTES-LOGINPRINCIPAL/background login.png"))); // NOI18N
        background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.setMaximumSize(new java.awt.Dimension(1440, 900));
        background.setMinimumSize(new java.awt.Dimension(1440, 900));
        background.setName(""); // NOI18N
        background.setOpaque(true);
        background.setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCadastrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCadastrarMouseClicked

    private void ButtonFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonFornecedorActionPerformed

    private void ButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastrarActionPerformed
    CADASTROUSUARIO novocadastro = new CADASTROUSUARIO();
    novocadastro.setVisible(true);
    }//GEN-LAST:event_ButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINPRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barracentral;
    private javax.swing.JToggleButton ButtonCadastrar;
    private javax.swing.JButton ButtonComprador;
    private javax.swing.JButton ButtonFornecedor;
    private javax.swing.JLabel background;
    private javax.swing.JLabel barrasenha;
    // End of variables declaration//GEN-END:variables
}
