/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package siaco.views;

/**
 *
 * @author Adrielly Rayssa
 */
public class LOGINCOMPRADOR extends javax.swing.JFrame {

    /**
     * Creates new form LOGINPRINCIPAL
     */
    public LOGINCOMPRADOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JFormattedTextField();
        Senha = new javax.swing.JPasswordField();
        recuperarsenha = new javax.swing.JButton();
        ButtonEntrar = new javax.swing.JButton();
        Logout = new javax.swing.JToggleButton();
        barrasenha = new javax.swing.JLabel();
        Barracentral = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1440, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setForeground(new java.awt.Color(153, 153, 153));
        try {
            Login.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, 400, 30));

        Senha.setForeground(new java.awt.Color(153, 153, 153));
        Senha.setText("Senha");
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 400, 30));

        recuperarsenha.setBackground(new java.awt.Color(0, 0, 0));
        recuperarsenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        recuperarsenha.setForeground(new java.awt.Color(0, 255, 255));
        recuperarsenha.setText("Recuperar Senha");
        recuperarsenha.setActionCommand("");
        recuperarsenha.setBorderPainted(false);
        recuperarsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarsenhaActionPerformed(evt);
            }
        });
        getContentPane().add(recuperarsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 610, 190, 40));

        ButtonEntrar.setBackground(new java.awt.Color(0, 0, 0));
        ButtonEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonEntrar.setText("Entrar");
        ButtonEntrar.setBorderPainted(false);
        getContentPane().add(ButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 510, 130, 70));

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.setBorderPainted(false);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 50, 190, 40));

        barrasenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTES-LOGINPRINCIPAL/Rectangle 2.png"))); // NOI18N
        getContentPane().add(barrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, 110));

        Barracentral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTES-LOGINPRINCIPAL/Group 5.png"))); // NOI18N
        Barracentral.setText("jLabel1");
        getContentPane().add(Barracentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1920, 230));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/COMPONENTES-LOGINPRINCIPAL/background login.png"))); // NOI18N
        background.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        background.setMaximumSize(new java.awt.Dimension(1440, 900));
        background.setMinimumSize(new java.awt.Dimension(1440, 900));
        background.setName(""); // NOI18N
        background.setOpaque(true);
        background.setPreferredSize(new java.awt.Dimension(1440, 900));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1110));

        setSize(new java.awt.Dimension(1932, 1135));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void recuperarsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recuperarsenhaActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGINCOMPRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGINCOMPRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGINCOMPRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGINCOMPRADOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGINCOMPRADOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barracentral;
    private javax.swing.JButton ButtonEntrar;
    private javax.swing.JFormattedTextField Login;
    private javax.swing.JToggleButton Logout;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JLabel background;
    private javax.swing.JLabel barrasenha;
    private javax.swing.JButton recuperarsenha;
    // End of variables declaration//GEN-END:variables
}
